### ISSUE TITLE
Compatibility with Now 2.0?

### ISSUE THREAD

**Issue by ewyler** [jkrup/meteor-now#133]
Not so much a feature request as it is a question/ask for confirmation - Now 2.0 unfortunately appears to have done away entirely with wrapping server/container instances and have instead decided to simply wrap AWS lambdas. (https://zeit.co/blog/now-2). The Spectrum forum has a short thread around web socket support which basically indicates it's not a thing anymore (as I expected when I read the announcement).

I assume this indicates an unfortunate early demise for this project as they've deprecated the old deployment flow and will eventually retire it, which is a bummer since Meteor + Now seemed a great combination.

**Comment by jkrup** [comment]
Yes and no!

Unfortunately with the current planned direction of Now, you're correct that it indicates MeteorJS will become essentially incompatible with Now. 

However, I won't let that be the end to this project. Which will remain the easiest/zero-config way to deploy meteor apps. I've actually have already experimented with deploys on a different platform that starts very cheap (<$2.50 mo), but unfortunately does not have a free tier.

I'll also try to reach out to some people at Zeit and see if they can help come up with a solution as well. @timneutkens 😉

**Comment by AshHimself** [comment]
@jkrup - Let me know how I can help out or test with other service as this project essentially runs my project :) 

Did they indicate when it would retire its current architecture and workflow?

**Comment by ewyler** [comment]
Great to hear! What's the other platform? Cheap is nearly the same as free, I wouldn't let minor cost dissuade integration with a quality platform.

**Comment by trinicoder** [comment]
Could this tool be used with any VPS (linode eg)?

**Comment by nabiltntn** [comment]
@trinicoder you can use https://github.com/zodern/meteor-up if you want to deploy to a VPS

**Comment by mukulhase** [comment]
Can you please update the website, I accidentally deployed it and all I see is this now. 
![image](https://user-images.githubusercontent.com/9693405/48304769-3fc24300-e545-11e8-923f-c3619349c731.png)

**Comment by jkrup** [comment]
Oh wow @mukulhase . That looks like something definitely went wrong... You probably want to delete that deploy in zeit `now` that as those `nbo.tar.gz.sf-*` contain the source code that you deployed. 

It looks like you somehow deployed with `now`v2.0, and it's just exposing everything in the directory. 

What version of `meteor-now` are you running? ```meteor-now --version`

**Comment by qualitymanifest** [comment]
@mukulhase did you ever get this working correctly? I found a setting that might fix this problem:

- Log on at zeit.co/now#
- Go to your account page https://zeit.co/account
- Scroll down to **Platform Version** and select **v1** (assuming it isn't selected already?) and click **save**

Then try deploying again. If you try this please let me know if it works.

**Comment by AshHimself** [comment]
AWS Amplify just got released. This could be an option.

**Comment by danieljonce** [comment]
I just ran into https://sandstorm.io, which looks interesting. I can imagine a scenario where, instead of bundling a meteor app to run on it, one may be able to build a meteor hosting "grain" that accepts a single meteor app deployment. Then spin up a new hosting grain anytime you need a place to deploy a new app. Looks Meteor friendly: https://docs.sandstorm.io/en/latest/vagrant-spk/platform-stacks/ and Jade Wang who previously worked Meteor is involved with it. Looks like they're targeting people who need personal and development use, so not exactly a complete Now replacement...but could be useful.

**Comment by ddresch** [comment]
I'm confused now. I deployed a few minutes ago and all is fine. So do I need to be afraid meteor-now is not working anymore with zeit in the next days?

**Comment by brianebill** [comment]
@ddresch in early November, Zeit announced they will be deprecating their version 1 product which supported meteor via docker (essentially what meteor-now does is package a meteor app as a docker image, so the host doesn't really matter that much except with regard to performance). Version 2 of Zeit does not support meteor out of the box, and so far no one has signed up to create the custom lambdas to support Meteor on version 2 of Zeit. 

In a year or so, Zeit may unplug version 1.0, but in the meantime, you can use it (though it's not clear how or when meteor-now will change as of yet per this discussion). In my case, I'm taking that year to re-write my applications to use lambdas as it will save money. For example, retaining point in time backups of my mongodb on atlas costs $70/month. I can reduce that cost to pennies per month by using react/appsync/dynamodb/lambdas. After having deployed a first app on Zeit 2.0 and seeing the performance gains over the same app on version 1.0, I'm convinced they're making the right choice, but it's caused many people, including yourself, to question their stack choices. 

The Meteor Group is working hard to ensure Apollo/GraphQL fits in nicely with react/graphql with lambdas or whatever on the backend. Meteor.js is a great way to develop a MVP, but the problem comes from the costs and limitations of hosting it. Galaxy, for example, is $28/month per application last time I checked, and there's no API for multiple domains. 

Thus, the meteor-now crew is filling a vital need and searching for another service, which will accommodate the docker method.

**Comment by jkrup** [comment]
@ddresch Unfortunately while there's no guarantee, I do have it on pretty good word from a current Zeit employee that we will have a fair amount of notice before v1 does shut down. The main alternative I was exploring recently announced they will be shutting down too (hyper.sh for the curious), so now I'm looking into other options.

**Comment by cdcv** [comment]
Really hope that you can figure out a solution as we LOVE meteor-now.  Thanks for creating and maintaining it.  Do the Zeit guys have openness to making Now 2 compatible one way or another / coming up with a solution??

**Comment by medied** [comment]
@jkrup just curious if you have an update on this?

**Comment by jkrup** [comment]
Hey @medied I have a small update! There's a post in the Zeit Spectrum chat where one of the employees (@mattheus) says you can quote him that Now v1.0 will not be deprecated at least until the end of 2019. So we definitely have a bit of time. Meanwhile, I'm exploring other options, but haven't made much progress yet.

**Comment by gustawdaniel** [comment]
I suggest to detect which version of now is installed in computer and display clear message, why it is not compatible, how about perspectives of now v1 and how to install now in v1, not v2 version.

People that today follows instruction:

> https://www.meteor-now.com/

experiencing error:

![screenshot from 2019-01-25 23-23-18](https://user-images.githubusercontent.com/16663028/51777434-5ff1af00-20fd-11e9-8be1-49e3a640d20f.png)

**Comment by juliomac** [comment]
Dear @jkrup , congratulations on your meteor-now project! 

Have you heard of these gigs from [WeDeploy](https://wedeploy.com) ? They have a pretty good installation process for Rocket.Chat which is a Meteor application. Aside from Rocket Chat I am still testing deploying other Meteor apps there but there isn't much information.

They have a free tier...

**Comment by moberegger** [comment]
Is there a workaround for this? Is it still even possible to deploy via v1? I have the platform configured to use v1 in my Zeit account (as suggested in https://github.com/jkrup/meteor-now/issues/133#issuecomment-440794157), and I also have a `now.json` file specifying v1:
```
{
  "version": 1
}
```

and receive the same errors shown in https://github.com/jkrup/meteor-now/issues/133#issuecomment-457763773. Using `now@14.0.3` and `meteor-now@0.8.0`.

**Comment by eybarta** [comment]
Hi, I'm looking for a Meteor deployment solution to use instead of Galaxy (which I'm currently using) and was about to try the meteor-now route until I saw this issue... 
Is there any clear answer to whether meteor-now will be available after 2019? 
I'm not looking for a free hosting solution but something more reasonable than Galaxy, can I trust meteor-now to be up and running even after the V1 Now service is gone?
thx for all your work!

**Comment by juliomac** [comment]
Update on Wedeploy... just received message that they will discontinue their service on April 22nd. Too bad as their service was awesome!

**Comment by Sburke0708** [comment]
@eybarta It sadly looks like no. https://github.com/zeit/now-builders/issues/11#issuecomment-450425953

**Comment by ralphievolt** [comment]
@jkrup is it possible to use AWS S3 instead of now using your procedure?

**Comment by YeapGuy** [comment]
@jkrup Any updates? meteor-now is still getting 25 weekly downloads, so it's quite popular and we all love it! Please, do not discontinue searching for an alternative platform!

**Comment by YeapGuy** [comment]
What about IBM Cloud? I saw this article and thought something like meteor-now could maybe work with this? (or maybe not, I have no idea how this stuff works): https://medium.com/@ptuton/how-to-build-and-deploy-a-meteor-application-on-ibm-bluemix-with-devops-services-974c0ba52529

**Comment by tdotholla** [comment]
is there at least some control in order to set environment variables back to mongodb server and mail server and just let node run the build `main.js` file? 
seems like using now v2 ALMOST works up until it tries to build with "meteor build" command line... since the `meteor` command not recognized on Zeit's environment.....

i thought building with meteor build and letting Zeit just run `node main.js` would work....

**Comment by jkrup** [comment]
# Announcing [Meteor-Hero](https://github.com/jkrup/meteor-hero)

After speaking with members of Zeit's team it seems it will unfeasible to ever get MeteorJS applications deployed on Now v2. 

So, I have created [meteor-hero](https://github.com/jkrup/meteor-hero) to deploy MeteorJS applications on [Heroku](https://heroku.com). 

The great thing about this, is unlike meteor-now, this will deploy a much more stable MongoDB instance with your application (assuming you don't bring-your-own).

Right now it's a lot less polished than meteor-now, but I'll work on making it a bit more convenient (better error messaging, etc.). It would be great to have people trying it out, running into errors and posting GH Issues, so I can iron out all the problems.

Overall though I'm really happy with the switch. Meteor-Hero actually builds the docker images locally instead of on `now`'s servers, which means you can always take advantage of docker's multi-layer caching (if you don't change `package.json` the apps deploy significantly faster). And as mentioned above, you can deploy a production-capable MongoDB instance with the single command instead of needing to bring your own. Meteor-Hero also has support for an `envFile` rather than having to pass in `-e [ENVVAR]`s too.

Taggging a few people who displayed significant interest in this update: @YeapGuy @ewyler @AshHimself @moberegger @juliomac
