### ISSUE TITLE
Extremely Long Build Times

### ISSUE THREAD

**Issue by rwatts3** [jkrup/meteor-now#52]
Greetings, 

I just tried to deploy a meteor app with meteor-now, and the build time took nearly 15 minutes. 
Are there any tips or gotchas' to help reduce the build time. 

This is important because when deploying hot fixes to an application with 15+ build times may not be an optimal solution.

**Comment by jkrup** [comment]
Specifying a `MONGO_URL`  with `-e MONGO_URL` will speed the build up as it will not need to install MongoDB and `supervisord`. Also 15 minutes is pretty long, so I wonder if your upload speed was a bit slow? You can try to run `meteor-now` with `-d` and see which steps are taking long times.

**Comment by johhansantana** [comment]
bad thing about meteor is that when deploying you have to bundle it up and then upload that bundle which I think in `now` it has to upload everything every time you make a change.

For everything else it works like a repository (only uploads stuff that has changed).

Makes me wonder if it would be possible to do something like deploying from a repository instead and make the `now` server do the bundle itself instead of the user. @jkrup

**Comment by rwatts3** [comment]
Yeah that would be ideal similar to how docker only checks the commit hash

**Comment by purplecones** [comment]
The thing is, **now** already does a pretty good hash diff to figure out which files to upload. With **meteor-now**, we bundle the app down to one file so the diff is mute. We did that so that the docker file can be lean and doesn't need the whole Meteor framework code and to get around the 1 mb limit on free plan. Since there is no limit anymore, we should look into other options.

There is a lot of room for improvement. I know **now** can deploy from github repos but haven't looked into it much. Not sure how it would work with private repos. @jkrup came across some really cool Docker Images for Meteor that perform well and have Meteor framework code on it. If we can use that, then there is no need to bundle the app locally, let **now** handle diffing and uploading changed files.

**Comment by rwatts3** [comment]
Yeah I like the idea

**Comment by arrygoo** [comment]
👍
