### ISSUE TITLE
Why does meteor-now make a server-only build?

### ISSUE THREAD

**Issue by vladejs** [jkrup/meteor-now#64]
I noticed this when deploying a meteor app:
`[METEOR-NOW] - running command: meteor build .meteor/local/builds --server-only --architecture=os.linux.x86_64`

why server-only param is being used?

**Comment by jkrup** [comment]
This is `--server-only` as opposed to server and mobile (i.e. cordova). So this is telling it to build everything required for the website / server. But not to build a mobile app when inside Docker. We wouldn't want to build a mobile app on the now server, however you could still create a cordova app and use this `--server-only` deploy as the `--mobile-server` for it's API/backend.

**Comment by sspathare97** [comment]
Could you please elaborate how to create the cordova app and use that --server-only deploy as the --mobile-server for it's API/backend?
I tried executing-
_meteor run android-device --mobile-server test-random.now.sh_
But it gives error -'Redirect has been blocked by CORS policy' since app is executing on localhost and sending xmlhttprequest request to target server.
I got the same results using-
_meteor build ../op --server test-random.now.sh:80_
Am I missing any steps?

**Comment by jkrup** [comment]
Do you have a `mobile-config.js` (https://docs.meteor.com/api/mobile-config.html) as per https://github.com/meteor/meteor/issues/3469#issuecomment-93701838 you may need to add a `App.accessRule('*')` (or your zeit domain if you want to be extra security conscious).
