### ISSUE TITLE
✖ [METEOR-NOW] - Something went wrong with now

### ISSUE THREAD

**Issue by lesliedoghouse** [jkrup/meteor-now#88]
Hi all, may I know what is the cause of this error? How to fix it? Please help.

Error! Too many active deployment instances
✖ [METEOR-NOW] - Something went wrong with now

**Comment by lesliedoghouse** [comment]
New observation.

Chances of getting deploy without error is higher if without MONGO_URL. But also not 100%.

Yesterday deploy with MONGO_URL no problem. Today unable to deploy success before.

**Comment by purplecones** [comment]
This feels like a `now` related issue as indicated by the error you got, there are too many active instances running under your account. The free plan I believe only allows you to have 3 active instances running at one time. It's important to note that by default, instances go to 'sleep' after inactivity after some duration of time. This is probably why you sometimes don't get the error when deploying because at that time.

Here is a related issue on this topic: https://github.com/zeit/now-cli/issues/647

**Comment by lesliedoghouse** [comment]
@purplecones Thanks for your advice. I didn't aware of the 3 instance limitation and I have removed unwanted deploy and the publish is fine now.
